export const ERROR = {
  PERFUME_NOT_FOUND: 'PERFUME_NOT_FOUND',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  FRAGRANCE_NOT_FOUND: 'FRAGRANCE_NOT_FOUND',
  ADD_FRAGRANCE_ERROR: 'ERROR.ADD_FRAGRANCE_ERROR',
  ADD_BRAND_ERROR: 'ADD_BRAND_ERROR',
  GET_FRAGRANCES_FAILED: 'GET_FRAGRANCES_FAILED',
  GET_BRANDS_FAILED:'GET_BRANDS_FAILED',
  
};
